version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stockdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/stockdb
    ports:
      - 8000:8000

volumes:
  db-data:
